let pool=[], index=0, selected=new Set(), examAnswers=[];
const state=JSON.parse(localStorage.getItem('aevoState')||'{"done":0,"right":0,"wrong":0,"wrongIds":[]}');
const $=id=>document.getElementById(id);
function save(){localStorage.setItem('aevoState',JSON.stringify(state));renderStats();renderWrongList();}
function renderStats(){ $('doneStat').textContent=state.done; $('rightStat').textContent=state.right; $('wrongStat').textContent=state.wrong; }
function renderWrongList(){const ul=$('wrongList'); ul.innerHTML=''; state.wrongIds.forEach(id=>{const q=QUESTIONS.find(x=>x.id===id); if(q){const li=document.createElement('li'); li.textContent=`${q.field}: ${q.topic} – ${q.q.slice(0,70)}…`; ul.appendChild(li);}});}
function shuffle(arr){return [...arr].sort(()=>Math.random()-.5)}
function start(){const f=$('fieldFilter').value; if(f==='wrong') pool=QUESTIONS.filter(q=>state.wrongIds.includes(q.id)); else pool=QUESTIONS.filter(q=>f==='all'||q.field===f); pool=shuffle(pool); index=0; examAnswers=[]; if(!pool.length){$('question').textContent='Keine Fragen in dieser Auswahl.';return} show();}
function show(){selected.clear(); const q=pool[index]; $('badge').textContent=`${q.field} · ${q.topic}`; $('progress').textContent=`Frage ${index+1}/${pool.length}`; $('question').textContent=q.q; $('meta').textContent=q.correct.length>1?`Mehrfachauswahl: ${q.correct.length} Antworten richtig`:'Einfachauswahl'; $('feedback').classList.add('hidden'); $('feedback').innerHTML=''; $('checkBtn').disabled=false; $('nextBtn').disabled=true; const answers=$('answers'); answers.innerHTML=''; q.a.forEach((txt,i)=>{const b=document.createElement('button'); b.className='answer'; b.textContent=String.fromCharCode(65+i)+') '+txt; b.onclick=()=>{ if(q.correct.length===1){selected.clear(); document.querySelectorAll('.answer').forEach(x=>x.classList.remove('selected'));} selected.has(i)?selected.delete(i):selected.add(i); b.classList.toggle('selected');}; answers.appendChild(b);});}
function arraysEqual(a,b){return a.length===b.length&&a.every(x=>b.includes(x));}
function check(){const q=pool[index]; const chosen=[...selected].sort(); if(!chosen.length)return; const correct=[...q.correct].sort(); const ok=arraysEqual(chosen,correct); const answerBtns=[...document.querySelectorAll('.answer')]; answerBtns.forEach((btn,i)=>{btn.disabled=true; if(correct.includes(i))btn.classList.add('correct'); if(chosen.includes(i)&&!correct.includes(i))btn.classList.add('wrong');}); const mode=$('mode').value; examAnswers.push({id:q.id,ok,chosen}); if(mode==='learn'){state.done++; ok?state.right++:state.wrong++; if(!ok&&!state.wrongIds.includes(q.id))state.wrongIds.push(q.id); if(ok)state.wrongIds=state.wrongIds.filter(id=>id!==q.id); save(); $('feedback').classList.remove('hidden'); $('feedback').innerHTML=`<strong>${ok?'Richtig':'Falsch'}.</strong><br>${q.exp}<br><br><strong>Merke:</strong> Richtige Antwort: ${correct.map(i=>String.fromCharCode(65+i)).join(', ')}`;} $('checkBtn').disabled=true; $('nextBtn').disabled=false; if(mode==='exam'&&index===pool.length-1) $('nextBtn').textContent='Auswertung'; else $('nextBtn').textContent='Nächste Frage';}
function next(){ if(index<pool.length-1){index++;show();return} if($('mode').value==='exam') finishExam(); }
function finishExam(){let right=examAnswers.filter(x=>x.ok).length; state.done+=examAnswers.length; state.right+=right; state.wrong+=examAnswers.length-right; examAnswers.forEach(x=>{ if(!x.ok&&!state.wrongIds.includes(x.id))state.wrongIds.push(x.id); if(x.ok)state.wrongIds=state.wrongIds.filter(id=>id!==x.id);}); save(); $('badge').textContent='Auswertung'; $('progress').textContent='Fertig'; $('question').textContent=`${right} von ${examAnswers.length} richtig`; $('answers').innerHTML=''; $('feedback').classList.remove('hidden'); $('feedback').innerHTML='Gehe nun in den Modus „Nur falsch beantwortete Fragen“, um gezielt deine Fehler zu trainieren.'; $('checkBtn').disabled=true; $('nextBtn').disabled=true;}
$('startBtn').onclick=start; $('checkBtn').onclick=check; $('nextBtn').onclick=next; $('resetBtn').onclick=()=>{localStorage.removeItem('aevoState'); location.reload();}; renderStats();renderWrongList();
