const FIELDS={HF1:'Ausbildungsvoraussetzungen prüfen und Ausbildung planen',HF2:'Ausbildung vorbereiten und bei der Einstellung mitwirken',HF3:'Ausbildung durchführen',HF4:'Ausbildung abschließen'};
const $=id=>document.getElementById(id);
const storeKey='aevo-masterkit-v2';
let state=JSON.parse(localStorage.getItem(storeKey)||'{}');
state.answers ||= {}; state.mistakes ||= []; state.exams ||= []; state.streak ||= {last:null,count:0};
let session=[],idx=0,selected=new Set(),examMode=false,examAnswers=[];
function save(){localStorage.setItem(storeKey,JSON.stringify(state));}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function show(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('show'));$(view).classList.add('show');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));renderAll()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.view));
function touchStreak(){let d=new Date().toISOString().slice(0,10); if(state.streak.last!==d){let y=new Date(Date.now()-864e5).toISOString().slice(0,10); state.streak.count=state.streak.last===y?(state.streak.count||0)+1:1; state.streak.last=d; save();}}
function stats(){let vals=Object.values(state.answers);let done=vals.length,right=vals.filter(x=>x.ok).length;return{done,right,wrong:state.mistakes.length,quote:done?Math.round(right/done*100):0}}
function renderAll(){let s=stats();$('totalQ').textContent=QUESTIONS.length;$('doneQ').textContent=s.done;$('quoteQ').textContent=s.quote+'%';$('wrongQ').textContent=s.wrong;$('streak').textContent=state.streak.count||0;renderFields();renderMistakes();renderStats()}
function renderFields(){let html='';for(let f of Object.keys(FIELDS)){let qs=QUESTIONS.filter(q=>q.field===f),done=qs.filter(q=>state.answers[q.id]).length,right=qs.filter(q=>state.answers[q.id]?.ok).length,p=done?Math.round(right/done*100):0;html+=`<div class="field"><b>${f}</b><p>${FIELDS[f]}</p><small>${done}/${qs.length} bearbeitet · ${p}% richtig</small><div class="line"><i style="width:${p}%"></i></div><button class="secondary" onclick="startLearn('${f}')">Trainieren</button></div>`}$('fieldCards').innerHTML=html}
function renderMistakes(){let box=$('mistakeList'); if(!box)return; let ids=[...new Set(state.mistakes)].slice(-80).reverse(); box.innerHTML=ids.length?ids.map(id=>{let q=QUESTIONS.find(x=>x.id==id);return q?`<div><b>${q.field} · ${q.topic}</b><br>${q.q}</div>`:''}).join(''):'<p>Keine offenen Fehler. Glückliche Katze! 😸</p>'}
function renderStats(){let box=$('statsBox'); if(!box)return; let s=stats();let html=`<div class="resultGrid"><div class="stat card"><span>Bearbeitet</span><b>${s.done}</b></div><div class="stat card"><span>Richtig</span><b>${s.right}</b></div><div class="stat card"><span>Quote</span><b>${s.quote}%</b></div></div><h3>Leistung nach Handlungsfeldern</h3>`;for(let f in FIELDS){let qs=QUESTIONS.filter(q=>q.field===f),done=qs.filter(q=>state.answers[q.id]).length,right=qs.filter(q=>state.answers[q.id]?.ok).length,p=done?Math.round(right/done*100):0;html+=`<p><b>${f}</b> ${FIELDS[f]} – ${p}% (${right}/${done||0})</p><div class="bar"><i style="width:${p}%"></i></div>`}html+='<h3>Letzte Prüfungen</h3>'+(state.exams.length?state.exams.slice(-10).reverse().map(e=>`<div class="hist"><b>${e.date}</b> · Score ${e.score}% · ${e.right}/${e.total} richtig</div>`).join(''):'<p>Noch keine Prüfung abgeschlossen.</p>');box.innerHTML=html}
function startLearn(filter='all'){show('learn');examMode=false;examAnswers=[];let pool=filter==='wrong'?QUESTIONS.filter(q=>state.mistakes.includes(q.id)):QUESTIONS.filter(q=>filter==='all'||q.field===filter);session=shuffle(pool);idx=0;renderQuestion()}
function startExam(){show('learn');examMode=true;examAnswers=[];session=shuffle(QUESTIONS).slice(0,80);idx=0;renderQuestion()}
function renderQuestion(){selected=new Set();$('feedback').className='feedback hidden';$('checkBtn').disabled=false;$('nextBtn').disabled=true;if(!session.length){$('question').textContent='Keine Fragen gefunden.';$('answers').innerHTML='';return}let q=session[idx];$('badge').textContent=(examMode?'Prüfung':'Lernen')+' · '+q.field;$('progress').textContent=`Frage ${idx+1}/${session.length}`;$('bar').style.width=((idx)/session.length*100)+'%';$('question').textContent=q.q;$('topic').textContent=q.topic+' · '+FIELDS[q.field]+(q.type==='multi'?' · Mehrfachauswahl':'');$('answers').innerHTML=q.a.map((a,i)=>`<label class="answer" data-i="${i}"><input type="${q.type==='multi'?'checkbox':'radio'}" name="ans"> <span>${a}</span></label>`).join('');document.querySelectorAll('.answer').forEach(el=>el.onclick=()=>{let i=+el.dataset.i;if(q.type!=='multi'){selected.clear();document.querySelectorAll('.answer').forEach(x=>x.classList.remove('selected'));}selected.has(i)?selected.delete(i):selected.add(i);el.classList.toggle('selected',selected.has(i));});}
function arraysEq(a,b){return a.length===b.length&&a.every(x=>b.includes(x))}
function checkAnswer(){let q=session[idx];let chosen=[...selected].sort((a,b)=>a-b);if(!chosen.length)return;let ok=arraysEq(chosen,q.correct);touchStreak();state.answers[q.id]={ok,field:q.field,topic:q.topic,ts:Date.now()}; if(ok) state.mistakes=state.mistakes.filter(id=>id!==q.id); else if(!state.mistakes.includes(q.id)) state.mistakes.push(q.id); save(); examAnswers.push({id:q.id,ok,field:q.field});document.querySelectorAll('.answer').forEach(el=>{let i=+el.dataset.i;if(q.correct.includes(i))el.classList.add('good');else if(chosen.includes(i))el.classList.add('bad')});$('checkBtn').disabled=true;$('nextBtn').disabled=false;let correctText=q.correct.map(i=>q.a[i]).join(' | ');$('feedback').className='feedback '+(ok?'ok':'bad');$('feedback').innerHTML=`<div class="catpic">${ok?'😸':'😿'}</div><h3>${ok?'Richtig! 🎉':'Leider falsch! 🐾'}</h3>${ok?'':`<p><b>Richtige Antwort:</b> ${correctText}</p>`}<p><b>Erklärung:</b> ${q.exp}</p>`;renderAll()}
function nextQuestion(){if(idx<session.length-1){idx++;renderQuestion()}else finishSession()}
function finishSession(){let right=examAnswers.filter(x=>x.ok).length,total=examAnswers.length,score=total?Math.round(right/total*100):0;if(examMode){let by={};for(let f in FIELDS)by[f]={r:0,t:0};examAnswers.forEach(x=>{by[x.field].t++;if(x.ok)by[x.field].r++});state.exams.push({date:new Date().toLocaleString('de-DE'),right,total,score,by});save();show('exam');$('examResult').className='card';$('examResult').innerHTML=`<h2>${score>=50?'Bestanden-Tendenz 😸':'Noch üben 😿'}</h2><div class="resultGrid"><div class="stat card"><span>Score</span><b>${score}%</b></div><div class="stat card"><span>Richtig</span><b>${right}/${total}</b></div><div class="stat card"><span>Fehler</span><b>${total-right}</b></div></div><h3>Auswertung</h3>`+Object.keys(by).map(f=>`<p><b>${f}</b> ${Math.round((by[f].r/(by[f].t||1))*100)}% (${by[f].r}/${by[f].t})</p><div class="bar"><i style="width:${Math.round((by[f].r/(by[f].t||1))*100)}%"></i></div>`).join('')+`<button onclick="startLearn('wrong')">Fehlertraining starten</button>`}else{$('question').textContent='Lernrunde beendet!';$('answers').innerHTML='';$('feedback').className='feedback ok';$('feedback').innerHTML='<div class="catpic">😸</div><h3>Stark gemacht!</h3><p>Deine Fehler wurden gespeichert und können im Fehlertraining wiederholt werden.</p>';$('nextBtn').disabled=true;$('checkBtn').disabled=true}renderAll()}
function resetAll(){if(confirm('Wirklich alle Scores und Fehler löschen?')){localStorage.removeItem(storeKey);location.reload()}}
renderAll();
