const $=id=>document.getElementById(id); const storeKey='aevo-masterkit-pro-v4';
let state=JSON.parse(localStorage.getItem(storeKey)||'{}'); state.mc ||= {}; state.cases ||= {}; state.mistakes ||= []; state.caseMistakes ||= []; state.exams ||= []; state.streak ||= {last:null,count:0};
let mcSession=[], mcIndex=0, chosen=new Set(), examMC=false, examAnswers=[];
let caseSession=[], caseIndex=0, examCases=false, currentCaseScore=0;
function save(){localStorage.setItem(storeKey,JSON.stringify(state));}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)} function pct(a,b){return b?Math.round(a/b*100):0}
function show(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('show'));$(v).classList.add('show');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));renderAll();}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.view));
function touch(){const d=new Date().toISOString().slice(0,10); if(state.streak.last!==d){const y=new Date(Date.now()-864e5).toISOString().slice(0,10); state.streak.count=state.streak.last===y?(state.streak.count||0)+1:1; state.streak.last=d; save();}}
function overall(){const mc=Object.values(state.mc), ca=Object.values(state.cases); const done=mc.length+ca.length; const right=mc.filter(x=>x.ok).length + ca.filter(x=>x.score>=60).length; return {done,right,rate:pct(right,done)};}
function renderAll(){const o=overall();$('mcCount').textContent=QUESTIONS.length; $('caseCount').textContent=CASES.length; $('doneCount').textContent=o.done; $('totalRate').textContent=o.rate+'%'; $('streak').textContent=state.streak.count||0; renderFields(); renderStats(); renderMistakes();}
function renderFields(){let html=''; for(const f in FIELDS){const m=QUESTIONS.filter(q=>q.field===f), c=CASES.filter(q=>q.field===f); const md=m.filter(q=>state.mc[q.id]).length, mr=m.filter(q=>state.mc[q.id]?.ok).length; const cd=c.filter(q=>state.cases[q.id]).length, cr=c.filter(q=>state.cases[q.id]?.score>=60).length; const rate=pct(mr+cr,md+cd); html+=`<div class="field"><b>${f}</b><h4>${FIELDS[f]}</h4><p>${m.length} MC · ${c.length} Fälle</p><div class="bar"><i style="width:${rate}%"></i></div><small>${md+cd} bearbeitet · ${rate}%</small><div class="row"><button onclick="startMC('${f}')">MC</button><button class="ghost" onclick="startCases('${f}')">Fälle</button></div></div>`} $('fieldCards').innerHTML=html;}
function startMC(filter='all', limit=null){show('learn'); examMC=false; examAnswers=[]; let pool=filter==='wrong'?QUESTIONS.filter(q=>state.mistakes.includes(q.id)):QUESTIONS.filter(q=>filter==='all'||q.field===filter); mcSession=shuffle(pool).slice(0,limit||pool.length); mcIndex=0; renderMC();}
function startFullExam(){show('exam'); examMC=true; examCases=true; examAnswers=[]; mcSession=shuffle(QUESTIONS).slice(0,80); caseSession=shuffle(CASES).slice(0,3); mcIndex=0; $('examResult').classList.add('hidden'); $('examBox').classList.remove('hidden'); renderExamMC();}
function renderExamMC(){renderMC(true); $('examBox').innerHTML=document.querySelector('#learn .quiz').innerHTML; show('learn');}
function renderMC(){chosen=new Set(); $('feedback').className='feedback hidden'; $('checkBtn').disabled=false; $('nextBtn').disabled=true; if(!mcSession.length){$('question').textContent='Keine Fragen gefunden.';$('answers').innerHTML='';return;} const q=mcSession[mcIndex]; $('badge').textContent=(examMC?'Prüfung':'Lernen')+' · '+q.field; $('progress').textContent=`Frage ${mcIndex+1}/${mcSession.length}`; $('bar').style.width=pct(mcIndex,mcSession.length)+'%'; $('topic').textContent=q.topic+' · '+FIELDS[q.field]+(q.type==='multi'?' · Mehrfachauswahl':''); $('question').textContent=q.q; $('answers').innerHTML=q.a.map((a,i)=>`<label class="answer" data-i="${i}"><input type="${q.type==='multi'?'checkbox':'radio'}" name="ans"><span>${a}</span></label>`).join(''); document.querySelectorAll('.answer').forEach(el=>el.onclick=()=>{const i=+el.dataset.i; if(q.type!=='multi'){chosen.clear();document.querySelectorAll('.answer').forEach(x=>x.classList.remove('selected'));} chosen.has(i)?chosen.delete(i):chosen.add(i); el.classList.toggle('selected',chosen.has(i));});}
function eq(a,b){return a.length===b.length&&a.every(x=>b.includes(x));}
function cat(ok){return `<div class="catWrap"><div class="${ok?'happyCat':'sadCat'}"></div></div>`;}
function checkMC(){const q=mcSession[mcIndex]; const arr=[...chosen].sort((a,b)=>a-b); if(!arr.length)return; const ok=eq(arr,q.correct); touch(); state.mc[q.id]={ok,field:q.field,topic:q.topic,date:Date.now()}; if(ok)state.mistakes=state.mistakes.filter(id=>id!==q.id); else if(!state.mistakes.includes(q.id))state.mistakes.push(q.id); save(); examAnswers.push({kind:'mc',field:q.field,ok,score:ok?1:0}); document.querySelectorAll('.answer').forEach(el=>{const i=+el.dataset.i; if(q.correct.includes(i))el.classList.add('good'); else if(arr.includes(i))el.classList.add('bad')}); $('checkBtn').disabled=true; $('nextBtn').disabled=false; $('feedback').className='feedback '+(ok?'ok':'bad'); $('feedback').innerHTML=`${cat(ok)}<h3>${ok?'Richtig! 🎉':'Leider falsch! 😿'}</h3>${ok?'':`<p><b>Richtig wäre:</b> ${q.correct.map(i=>q.a[i]).join(' · ')}</p>`}<p><b>Erklärung:</b> ${q.exp}</p>`; renderAll();}
function nextMC(){ if(mcIndex<mcSession.length-1){mcIndex++; renderMC();} else { if(examMC){caseIndex=0; startExamCases();} else {$('question').textContent='Runde beendet'; $('answers').innerHTML=''; $('feedback').className='feedback ok'; $('feedback').innerHTML=cat(true)+'<h3>Stark gemacht!</h3><p>Fehler wurden gespeichert.</p>'; $('checkBtn').disabled=true;$('nextBtn').disabled=true;} } }
function startCases(filter='all'){show('cases'); examCases=false; let pool=filter==='wrong'?CASES.filter(c=>state.caseMistakes.includes(c.id)):CASES.filter(c=>filter==='all'||c.field===filter); caseSession=shuffle(pool); caseIndex=0; renderCase();}
function renderCase(container='caseBox'){if(!caseSession.length){$(container).innerHTML='<h2>Keine Fälle gefunden.</h2>';return;} const c=caseSession[caseIndex]; $(container).innerHTML=`<div class="quizTop"><span class="pill">${c.field} · ${c.topic}</span><span>Fall ${caseIndex+1}/${caseSession.length}</span></div><div class="bar"><i style="width:${pct(caseIndex,caseSession.length)}%"></i></div><h2>${c.title}</h2><p class="situation">${c.situation}</p>${c.mixed?`<div class="miniMC"><b>${c.mixed.q}</b>${c.mixed.a.map((a,i)=>`<label class="answer small" data-mix="${i}"><input type="radio" name="mix"><span>${a}</span></label>`).join('')}</div>`:''}<h3>Aufgabe</h3><p>${c.tasks}</p><textarea id="caseAnswer" placeholder="Schreibe deine Antwort wie in der Prüfung..."></textarea><div class="row"><button onclick="checkCase('${container}')">Antwort auswerten</button><button class="ghost" onclick="nextCase('${container}')">Überspringen</button></div><div id="caseFeedback" class="feedback hidden"></div>`; document.querySelectorAll('[data-mix]').forEach(el=>el.onclick=()=>{document.querySelectorAll('[data-mix]').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')});}
function checkCase(container='caseBox'){const c=caseSession[caseIndex]; const text=($('caseAnswer')?.value||'').toLowerCase(); let hits=c.keywords.filter(k=>text.includes(k.toLowerCase().split('/')[0])); let mixOK=true; if(c.mixed){const sel=document.querySelector('[data-mix].selected'); mixOK=sel && c.mixed.correct.includes(+sel.dataset.mix); if(mixOK)hits.push('Auswahlfrage korrekt');}
 let score=pct(hits.length,c.keywords.length+(c.mixed?1:0)); touch(); state.cases[c.id]={score,field:c.field,topic:c.topic,date:Date.now()}; if(score>=60)state.caseMistakes=state.caseMistakes.filter(id=>id!==c.id); else if(!state.caseMistakes.includes(c.id))state.caseMistakes.push(c.id); save(); examAnswers.push({kind:'case',field:c.field,ok:score>=60,score:score/100}); const ok=score>=60; $('caseFeedback').className='feedback '+(ok?'ok':'bad'); $('caseFeedback').innerHTML=`${cat(ok)}<h3>${score}% erreicht · ${ok?'gut':'noch ausbaufähig'}</h3><p><b>Getroffene Punkte:</b> ${hits.length?hits.join(', '):'noch keine erkannten Kernpunkte'}</p><p><b>Musterlösung:</b> ${c.model}</p><p><b>Bewertungshinweis:</b> In der echten IHK-Prüfung zählt die fachliche Begründung. Diese App bewertet per Schlüsselbegriffen und ersetzt keine Prüferbewertung.</p><button onclick="nextCase('${container}')">Weiter</button>`; renderAll();}
function nextCase(container='caseBox'){ if(caseIndex<caseSession.length-1){caseIndex++; renderCase(container);} else { if(examCases && container==='examBox'){finishExam();} else {$(container).innerHTML=`${cat(true)}<h2>Fallrunde beendet.</h2><p>Scores und Fehlerfälle wurden gespeichert.</p>`;} } }
function startExamCases(){show('exam'); $('examBox').classList.remove('hidden'); caseIndex=0; renderCase('examBox');}
function finishExam(){const total=examAnswers.length; const raw=examAnswers.reduce((s,x)=>s+x.score,0); const score=pct(raw,total); const right=examAnswers.filter(x=>x.ok).length; const by={}; for(const f in FIELDS)by[f]={r:0,t:0}; examAnswers.forEach(x=>{by[x.field].t++; by[x.field].r+=x.score}); state.exams.push({date:new Date().toLocaleString('de-DE'),score,right,total,by}); save(); $('examResult').classList.remove('hidden'); $('examBox').classList.add('hidden'); $('examResult').innerHTML=`${cat(score>=50)}<h2>Prüfung abgeschlossen: ${score}%</h2><div class="cards compact"><div class="card"><span>Score</span><b>${score}%</b></div><div class="card"><span>Bestanden-Tendenz</span><b>${score>=50?'Ja':'Noch üben'}</b></div><div class="card"><span>Aufgaben</span><b>${total}</b></div></div><h3>Auswertung nach Handlungsfeldern</h3>${Object.keys(by).map(f=>`<p><b>${f}</b> ${pct(by[f].r,by[f].t)}%</p><div class="bar"><i style="width:${pct(by[f].r,by[f].t)}%"></i></div>`).join('')}<button onclick="show('stats')">Details ansehen</button>`; renderAll();}
function renderMistakes(){const box=$('mistakeList'); if(!box)return; const m=state.mistakes.slice(-25).reverse().map(id=>QUESTIONS.find(q=>q.id===id)).filter(Boolean); const c=state.caseMistakes.slice(-25).reverse().map(id=>CASES.find(q=>q.id===id)).filter(Boolean); box.innerHTML=(m.length||c.length)?`<h3>MC-Fehler</h3>${m.map(q=>`<div><b>${q.field} · ${q.topic}</b><p>${q.q}</p></div>`).join('')}<h3>Fall-Fehler</h3>${c.map(q=>`<div><b>${q.field} · ${q.topic}</b><p>${q.title}</p></div>`).join('')}`:'<p>Keine Fehler offen. 😸</p>';}
function renderStats(){const box=$('statsBox'); if(!box)return; const o=overall(); let html=`<div class="cards compact"><div class="card"><span>Bearbeitet</span><b>${o.done}</b></div><div class="card"><span>Richtig/gut</span><b>${o.right}</b></div><div class="card"><span>Quote</span><b>${o.rate}%</b></div></div><h3>Handlungsfelder</h3>`; for(const f in FIELDS){const m=QUESTIONS.filter(q=>q.field===f), c=CASES.filter(q=>q.field===f); const md=m.filter(q=>state.mc[q.id]).length, mr=m.filter(q=>state.mc[q.id]?.ok).length; const cd=c.filter(q=>state.cases[q.id]).length, cr=c.filter(q=>state.cases[q.id]?.score>=60).length; const r=pct(mr+cr,md+cd); html+=`<p><b>${f}</b> ${FIELDS[f]} – ${r}% (${md+cd} bearbeitet)</p><div class="bar"><i style="width:${r}%"></i></div>`;} html+=`<h3>Prüfungsverlauf</h3>${state.exams.length?state.exams.slice(-10).reverse().map(e=>`<div class="hist"><b>${e.date}</b><span>${e.score}% · ${e.total} Aufgaben</span></div>`).join(''):'<p>Noch keine Prüfung abgeschlossen.</p>'}`; box.innerHTML=html;}
function resetAll(){if(confirm('Alle lokalen Scores löschen?')){localStorage.removeItem(storeKey);location.reload();}}
renderAll();
