const FIELDS={
 HF1:'Ausbildungsvoraussetzungen prüfen und Ausbildung planen',
 HF2:'Ausbildung vorbereiten und bei der Einstellung mitwirken',
 HF3:'Ausbildung durchführen',
 HF4:'Ausbildung abschließen'
};
const TOPICS={
 HF1:['Vorteile der Ausbildung','Duales System','BBiG-Grundlagen','Ausbildungsordnung','Ausbildungsrahmenplan','Betrieblicher Ausbildungsplan','Eignung des Betriebs','Persönliche Eignung','Fachliche Eignung','Lernorte','Ausbildungsbedarf','Berufsausbildungsvorbereitung','Kooperation Berufsschule','Verb Verbundausbildung','Zuständige Stelle'],
 HF2:['Bewerberauswahl','AGG','Vorstellungsgespräch','Ausbildungsvertrag','Eintragung IHK','Probezeit','Ärztliche Erstuntersuchung','JArbSchG','Datenschutz','Onboarding','Berufsschulanmeldung','Ausbildungsnachweis','Tarifvertrag','Betriebsrat/JAV','Ausbildungsvergütung'],
 HF3:['Lernziele','Taxonomie','Kognitiv-affektiv-psychomotorisch','Vier-Stufen-Methode','Leittextmethode','Projektmethode','Lehrgespräch','Motivation','Feedback','Kommunikation','Konfliktgespräch','Lernschwierigkeiten','Lernerfolgskontrolle','Beurteilung','Interkulturelle Kompetenz','Arbeitssicherheit','Unterweisung planen','Selbstständiges Lernen'],
 HF4:['Zwischenprüfung','Gestreckte Abschlussprüfung','Prüfungsanmeldung','Zulassungsvoraussetzungen','Prüfungsvorbereitung','Ausbildungszeugnis','Einfaches Zeugnis','Qualifiziertes Zeugnis','Übernahmegespräch','Weiterbildung','Beendigung Ausbildung','Kündigung nach Probezeit','Nichtbestehen Prüfung','Verkürzung Verlängerung','Karrierewege']
};
const MC=[]; const CASES=[];
function add(field,topic,q,a,correct,exp,type='single'){MC.push({id:'M'+(MC.length+1),kind:'mc',field,topic,q,a,correct,exp,type});}
function addCase(field,topic,title,situation,tasks,model,keywords,points=10,mixed=null){CASES.push({id:'C'+(CASES.length+1),kind:'case',field,topic,title,situation,tasks,model,keywords,points,mixed});}
const templates=[
 ['Welche Aussage ist zum Thema „{topic}“ AEVO-gerecht?',['Der Ausbilder plant, erklärt, begleitet und dokumentiert angemessen.','Der Auszubildende muss alles ohne Anleitung selbst herausfinden.','Rechtliche Regeln sind nur Empfehlungen.','Probleme werden grundsätzlich zuerst mit Kündigung gelöst.'],[0],'AEVO-gerecht ist ein planvolles, pädagogisches und rechtssicheres Vorgehen.'],
 ['Was ist bei „{topic}“ in der Regel der erste sinnvolle Schritt?',['Sachverhalt klären und Ziel/Vorgehen planen.','Sofort bestrafen.','Nichts dokumentieren.','Auszubildende vor der Gruppe bloßstellen.'],[0],'In Prüfungssituationen gilt meist: erst analysieren, sprechen, planen, dann verhältnismäßig handeln.'],
 ['Welche zwei Punkte passen typischerweise zu „{topic}“?',['Klare Information','Dokumentation','Willkürliche Behandlung','Private Strafe'],[0,1],'Klare Information und Dokumentation sind prüfungsnah. Willkür und private Strafen sind falsch.','multi'],
 ['Welche Handlung wäre beim Thema „{topic}“ problematisch?',['Unsachliche Benachteiligung oder Bloßstellung.','Förderliches Feedback.','Abstimmung mit Lernorten.','Lernziele transparent machen.'],[0],'Benachteiligung, Bloßstellung und Willkür widersprechen der Ausbilderrolle.'],
 ['Welche Formulierung passt zu guter Ausbildung beim Thema „{topic}“?',['Lernziel, Methode und Kontrolle werden nachvollziehbar festgelegt.','Der Azubi wird ohne Rückmeldung alleine gelassen.','Es wird ausschließlich nach Bauchgefühl bewertet.','Die Berufsschule wird immer ignoriert.'],[0],'Gute Ausbildung verbindet Ziele, Methoden, Unterstützung und Kontrolle.'],
 ['Was prüft die IHK bei AEVO-Aufgaben häufig indirekt?',['Ob die Reaktion pädagogisch sinnvoll und rechtlich vertretbar ist.','Ob der Ausbilder möglichst streng wirkt.','Ob Gespräche vermieden werden.','Ob Gesetze ignoriert werden können.'],[0],'Viele Aufgaben sind Fallentscheidungen: angemessen, rechtssicher, lernförderlich.']
];
for(const f of Object.keys(TOPICS)){for(const t of TOPICS[f]){for(let r=0;r<6;r++){const x=templates[r];add(f,t,x[0].replaceAll('{topic}',t),x[1],x[2],x[3],x[4]||'single');}}}
[
 ['HF2','JArbSchG','Ein 17-jähriger Auszubildender soll regulär beschäftigt werden. Welche tägliche Höchstarbeitszeit gilt grundsätzlich?',['8 Stunden','9 Stunden','10 Stunden','12 Stunden'],[0],'Jugendliche dürfen grundsätzlich höchstens 8 Stunden täglich und 40 Stunden wöchentlich arbeiten.'],
 ['HF2','Probezeit','Welche Probezeit ist im Berufsausbildungsverhältnis nach BBiG vorgesehen?',['Mindestens 1 Monat, höchstens 4 Monate','Genau 6 Monate','Keine Probezeit','Beliebig lange'],[0],'Die Probezeit muss mindestens einen Monat und darf höchstens vier Monate dauern.'],
 ['HF2','Ausbildungsvertrag','Wer unterschreibt bei minderjährigen Auszubildenden den Ausbildungsvertrag mit?',['Gesetzliche Vertreter','Nur die Berufsschule','Nur der Betriebsrat','Niemand zusätzlich'],[0],'Bei Minderjährigen sind die gesetzlichen Vertreter einzubeziehen.'],
 ['HF3','Lernziele','Welche Lernzielbereiche werden klassisch unterschieden?',['Kognitiv, affektiv, psychomotorisch','Kurz, mittel, lang','Intern, extern, privat','Brutto, netto, tariflich'],[0],'Prüfungsrelevant sind kognitive, affektive und psychomotorische Lernziele.'],
 ['HF3','Vier-Stufen-Methode','Welche Reihenfolge passt zur Vier-Stufen-Methode?',['Vorbereiten – Vormachen/Erklären – Nachmachen lassen – Üben','Fragen – Kündigen – Melden – Archivieren','Lesen – Schweigen – Bewerten – Gehen','Prüfen – Strafen – Ignorieren – Wiederholen'],[0],'Die Vier-Stufen-Methode eignet sich besonders für praktische Fertigkeiten.'],
 ['HF4','Ausbildungszeugnis','Was enthält ein einfaches Ausbildungszeugnis mindestens?',['Art, Dauer und Ziel der Ausbildung sowie erworbene Fertigkeiten/Kenntnisse','Nur private Einschätzungen','Nur Fehltage','Nur Berufsschulnoten'],[0],'Das einfache Zeugnis beschreibt die Ausbildung und die erworbenen beruflichen Fähigkeiten.'],
 ['HF4','Nichtbestehen Prüfung','Was passiert bei Nichtbestehen der Abschlussprüfung auf Verlangen des Auszubildenden?',['Das Ausbildungsverhältnis verlängert sich bis zur nächstmöglichen Wiederholungsprüfung, höchstens um ein Jahr.','Es endet immer sofort.','Es verlängert sich unbegrenzt.','Die Probezeit beginnt erneut.'],[0],'Bei Nichtbestehen kann Verlängerung bis zur nächsten Wiederholungsprüfung verlangt werden, maximal ein Jahr.'],
 ['HF1','Eignung','Welche zwei Eignungen sind für Ausbilder besonders relevant?',['Persönliche Eignung','Fachliche Eignung','Musikalische Eignung','Private Eignung'],[0,1],'Ausbilder müssen persönlich und fachlich geeignet sein.','multi'],
 ['HF2','AGG','Welche Kriterien dürfen bei der Bewerberauswahl nicht benachteiligend verwendet werden?',['Herkunft/Religion/Geschlecht','Passende berufliche Interessen','Schulische Leistung, soweit relevant','Motivation für den Beruf'],[0],'Das AGG schützt vor Benachteiligungen aus den geschützten Gründen.'],
 ['HF3','Feedback','Welche zwei Merkmale hat gutes Feedback?',['Konkret','Zeitnah','Abwertend','Öffentlich bloßstellend'],[0,1],'Feedback sollte konkret, zeitnah, respektvoll und verhaltensbezogen sein.','multi']
].forEach(x=>add(...x));
const baseCases={
 HF1:['Ausbildungsplanung','Ihr Betrieb möchte erstmals ausbilden. Die Geschäftsleitung erwartet eine kurze Einschätzung, ob und wie die Ausbildung gestartet werden kann.','Beschreiben Sie die wichtigsten Prüfschritte.','Betriebliche Eignung prüfen, Ausbildungsordnung und Ausbildungsrahmenplan heranziehen, sachlichen und zeitlichen Ausbildungsplan ableiten, geeigneten Ausbilder benennen, Lernorte/Berufsschule abstimmen und die zuständige Stelle einbeziehen.',['Eignung','Ausbildungsordnung','Ausbildungsplan','Ausbilder','IHK','Berufsschule']],
 HF2:['Einstellung minderjähriger Azubi','Eine 16-jährige Bewerberin soll eingestellt werden. Der Betrieb möchte möglichst schnell starten.','Beschreiben Sie Ihr Vorgehen bis zum Ausbildungsbeginn.','Fair auswählen und AGG beachten, Ausbildungsvertrag vorbereiten, gesetzliche Vertreter einbeziehen, ärztliche Erstuntersuchung beachten, Eintragung/Anmeldung bei zuständiger Stelle und Berufsschule organisieren, Einführung planen.',['AGG','Vertrag','gesetzliche Vertreter','Erstuntersuchung','IHK','Berufsschule']],
 HF3:['Leistungs- und Verhaltensproblem','Ein Auszubildender kommt wiederholt zu spät, wirkt unmotiviert und macht mehr Fehler. Die Fachabteilung fordert sofortige harte Konsequenzen.','Formulieren Sie ein pädagogisch und rechtlich sinnvolles Vorgehen.','Gespräch unter vier Augen führen, Ursachen klären, Erwartungen transparent machen, Unterstützung anbieten, klare Vereinbarungen treffen, dokumentieren, Entwicklung kontrollieren und bei Wiederholung verhältnismäßige arbeitsrechtliche Schritte prüfen.',['Gespräch','Ursachen','Unterstützung','Vereinbarung','Dokumentation','Abmahnung']],
 HF4:['Prüfungsvorbereitung','Eine Auszubildende hat Angst vor der Abschlussprüfung und zeigt Lücken in mehreren Lernbereichen.','Welche Maßnahmen planen Sie als Ausbilder?','Prüfungsanforderungen klären, Lernstand feststellen, Lernplan erstellen, praktische und schriftliche Übungen durchführen, Feedback geben, Fristen/Anmeldung prüfen und Perspektiven wie Übernahme oder Weiterbildung besprechen.',['Prüfungsanforderungen','Lernstand','Lernplan','Übung','Feedback','Fristen']]
};
for(const f of Object.keys(TOPICS)){for(const t of TOPICS[f]){const b=baseCases[f];addCase(f,t,`${b[0]} – Schwerpunkt ${t}`,b[1]+` Schwerpunkt ist: ${t}.`,b[2],b[3],b[4],10);addCase(f,t,`Kombifall – ${t}`,`In einer Ausbildungssituation zum Thema ${t} müssen Sie zuerst eine Entscheidung treffen und danach Ihr Vorgehen begründen.`,`1) Beantworten Sie die Auswahlfrage. 2) Formulieren Sie danach Ihr Vorgehen.`,b[3],b[4],10,{q:`Welche erste Reaktion ist beim Thema ${t} meistens am besten?`,a:['Sachverhalt prüfen und Gespräch/Vorgehen planen','Sofort kündigen','Öffentlich kritisieren','Problem ignorieren'],correct:[0]});}}
window.FIELDS=FIELDS; window.QUESTIONS=MC; window.CASES=CASES;
